services:
    frankenphp:
        build:
          context: .
          dockerfile: frankenphp.dockerfile
        volumes:
            - ../code/:/app:z
        environment:
            - "DB_PORT=5432"
            - "DB_HOST=database"
        tty: true
        ports:
          - "80:80"
          - "443:443"
          - "443:443/udp"

    database:
        build:
            context: .
            dockerfile: database.dockerfile
        volumes:
            - ../data:/var/lib/postgresql/data/pgdata:z
        environment:
            - "POSTGRES_USER=scrapbook"
            - "POSTGRES_PASSWORD=scrapbook"
            - "POSTGRES_DB=scrapbook"
            - "PGDATA=/var/lib/postgresql/data/pgdata"
        ports:
            - "5432:5432"
