version: '3'
services:
    interpreter:
        build:
            context: .
            dockerfile: interpreter.dockerfile
            args:
                - INSTALL_XDEBUG=${INTERPRETER_INSTALL_XDEBUG}
        working_dir: /var/www
        volumes:
            - ../code:/var/www:z
        environment:
            - "DB_PORT=5432"
            - "DB_HOST=database"
        tty: true

    webserver:
        build:
            context: .
            dockerfile: webserver.dockerfile
        working_dir: /var/www
        volumes_from:
            - interpreter
        volumes:
            - ./logs:/var/log/nginx:z
        ports:
            - 8080:80
        depends_on:
            - interpreter

    database:
        image: postgres:14.1-alpine
        volumes:
            - ../data:/var/lib/postgresql/data/pgdata:z
        environment:
            - "POSTGRES_USER=scrapbook"
            - "POSTGRES_PASSWORD=scrapbook"
            - "POSTGRES_DB=scrapbook"
            - "PGDATA=/var/lib/postgresql/data/pgdata"
        ports:
            - "5432:5432"
